version: '3.9'
services:
  web:
    container_name: web
    build: .
    ports:
      - '8000:8000'
    volumes:
      - .:/app
    depends_on:
      - db
  db:
    container_name: sebastian-db
    image: mysql
    environment:
      MYSQL_DATABASE: sebastian
      MYSQL_ROOT_PASSWORD: root
      MYSQL_ALLOW_EMPTY_PASSWORD: yes
    ports:
      - '3306:3306'
    volumes:
      - ./initdb.d/:/docker-entrypoint-initdb.d/
